[workspace]
members = [
    "contract/src/pair-contract",
    "contract/src/factory-contract",
    "contract/src/router-contract"
]
default-members = [
    "contract/src/pair-contract",
    "contract/src/router-contract",
    "contract/src/factory-contract"
]

[profile.release]
codegen-units = 1
lto = true