[workspace]
members = [
    "contracts/pair-contract",
    "contracts/router-contract",
    "tests"
]
default-members = [
    "contracts/pair-contract",
    "contracts/router-contract",
    "tests"
]

[profile.release]
codegen-units = 1
lto = true